
import type { RawSurveyResponse } from '../types';

export const RAW_DATA: RawSurveyResponse[] = [
  {
    "Timestamp": "9/16/2025 22:43:04",
    "Email Address": "adityakahar61@gmail.com",
    "Name": "",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Occasionally",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 0:21:19",
    "Email Address": "pritideshmukh2007@gmail.com",
    "Name": "",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 8:32:02",
    "Email Address": "nirmalkrishna995@gmail.com",
    "Name": "Abhimanyu ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Working / Professional",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 8:33:04",
    "Email Address": "mitaligotpagar@gmail.com",
    "Name": "Mitali Gotpagar ",
    "What is your age group?": "Below 18",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Online banking / transactions",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 9:14:37",
    "Email Address": "tanvi090307@gmail.com",
    "Name": "Tanvi Vitthal Baviskar ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 9:17:13",
    "Email Address": "realraj2006@gmail.com",
    "Name": "Real Raj Tiwari ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 9:29:50",
    "Email Address": "mishranidhi6002@gmail.com",
    "Name": "Nidhi Mishra ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/18/2025 10:09:14",
    "Email Address": "dunudunu632@gmail.com",
    "Name": "Archana ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/21/2025 19:15:44",
    "Email Address": "sharvanmaurya674@gmail.com",
    "Name": "Sharvan Maurya ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 19:59:45",
    "Email Address": "sayalijadhav2007@gmail.com",
    "Name": "Sayali Jadhav ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Streaming videos / music",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:21:11",
    "Email Address": "nadeemakh405@gmail.com",
    "Name": "Umair",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Use my own data",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:21:44",
    "Email Address": "juveriyasoni@gmail.com",
    "Name": "Juveriya ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "College ",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:22:09",
    "Email Address": "ahzamkhan8211@gmail.com",
    "Name": "ahzam",
    "What is your age group?": "26 - 35",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:22:45",
    "Email Address": "juveriya.khan@universal.edu.in",
    "Name": "Soni",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:27:44",
    "Email Address": "khanrig@gmail.com",
    "Name": "Aslam Khan ",
    "What is your age group?": "35 - 50",
    "What is your occupation?": "Working / Professional",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Hotels ",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/22/2025 20:30:30",
    "Email Address": "huzaifakhan9129@gmail.com",
    "Name": "Huzaifa Khan",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Never",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Don’t use",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/23/2025 9:08:09",
    "Email Address": "maazkhan1582001@gmail.com",
    "Name": "Mohd Maaz",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Business / Entrepreneur",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "N/A",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "N/A",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/23/2025 16:07:39",
    "Email Address": "aaryansingh24082005@gmail.com",
    "Name": "Aaryan",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/23/2025 16:20:08",
    "Email Address": "catchysmellsbyitmaaz@gmail.com",
    "Name": "Mehmood Shaikh ",
    "What is your age group?": "26 - 35",
    "What is your occupation?": "Business / Entrepreneur",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "No I don't connect i can't trust that my data is safe  ",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "No",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/23/2025 17:21:30",
    "Email Address": "kaushal.g.kollabathula@gmail.com",
    "Name": "Kaushal",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Working / Professional",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "I don’t",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "I usually avoid using public WiFi.",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/23/2025 22:20:26",
    "Email Address": "trulyimmortal80085@gmail.com",
    "Name": "Joseph Stalin ",
    "What is your age group?": "35 - 50",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:29:10",
    "Email Address": "trxvision31@gmail.com",
    "Name": "Shafi memon",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "None",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "None",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:29:51",
    "Email Address": "queen66jeyashree@gmail.com",
    "Name": "jeyashree",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:31:02",
    "Email Address": "srihithashetty@gmail.com",
    "Name": "Srihitha ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:34:41",
    "Email Address": "shaziya2005syed@gmail.com",
    "Name": "Shazia",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Shopping malls",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online banking / transactions",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:34:53",
    "Email Address": "samarthnivadunge@gmail.com",
    "Name": "Samarth Harishchandra Nivadunge ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Working / Professional",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online banking / transactions",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:37:15",
    "Email Address": "govindyadav1132@gmail.com",
    "Name": "Govind",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Weekly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:45:25",
    "Email Address": "pragnaskumar2@gmail.com",
    "Name": "Pragna S",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Shopping malls",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 20:52:12",
    "Email Address": "shifabehlim854@gmail.com",
    "Name": "Behlim shifa asif ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Library ",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 21:28:12",
    "Email Address": "aaronfreefire01@gmail.com",
    "Name": "Bheem",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Shopping malls",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 21:58:54",
    "Email Address": "undertakingboy@gmail.com",
    "Name": "Udhav Narendra Patil",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 22:07:54",
    "Email Address": "aadhiaadhith22@gmail.com",
    "Name": "Aadhith krishna",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Weekly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 22:32:36",
    "Email Address": "masira252@gmail.com",
    "Name": "Masira shaikh",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/25/2025 22:54:48",
    "Email Address": "prasadkale703@gmail.com",
    "Name": "Prasad kale ",
    "What is your age group?": "Below 18",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Not doing",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 0:37:31",
    "Email Address": "emadkhan9c27@gmail.com",
    "Name": "Emad Khan",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 0:44:25",
    "Email Address": "khanrayyan277a@gmail.com",
    "Name": "Rayyan khan ",
    "What is your age group?": "Below 18",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 6:34:49",
    "Email Address": "sagarguptaz2347@gmail.com",
    "Name": "Sagar Gupta ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 6:49:46",
    "Email Address": "ombhatane1@gmail.com",
    "Name": "Omkar ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Streaming videos / music",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Business owners providing Wi-Fi",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 7:36:28",
    "Email Address": "karanyadav122006@gmail.com",
    "Name": "Karan yadav ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 9:32:23",
    "Email Address": "eshamaurya696@gmail.com",
    "Name": "Esha maurya",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Shopping malls",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 15:22:12",
    "Email Address": "habeebashar14@icloud.com",
    "Name": "Habeebul Bashar MR",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 16:08:57",
    "Email Address": "siddhijagtap434@gmail.com",
    "Name": "Siddhi pradeep jagtap ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Streaming videos / music",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "VPN (Virtual Private Network)",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 22:47:47",
    "Email Address": "nitujha1503@gmail.com",
    "Name": "Divya jha",
    "What is your age group?": "Below 18",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Shopping malls",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Email / work-related tasks",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 22:50:27",
    "Email Address": "abhijeetsharma9539@gmail.com",
    "Name": "Abhijeet",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/26/2025 22:51:53",
    "Email Address": "sauravjha9757@gmail.com",
    "Name": "Saurav Jha",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Streaming videos / music",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/27/2025 11:16:07",
    "Email Address": "jchandan240@gmail.com",
    "Name": "Chandan jha",
    "What is your age group?": "26 - 35",
    "What is your occupation?": "Business / Entrepreneur",
    "How often do you use public wifi?": "Weekly",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Online banking / transactions",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/27/2025 12:59:00",
    "Email Address": "raj.khergamkar15@gmail.com",
    "Name": "Raj Khergamkar ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Hotspot",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Speed and reliability",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/27/2025 13:04:01",
    "Email Address": "vivovibo732@gmail.com",
    "Name": "Kishan jha ",
    "What is your age group?": "Below 18",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Weekly",
    "Where do you most often connect to public wifi?": "Homes ",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Streaming videos / music",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No specific precautions taken",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Mobile data",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Free access",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Government",
    "Score": ""
  },
  {
    "Timestamp": "9/27/2025 17:53:16",
    "Email Address": "anjujha2454@gmail.com",
    "Name": "Anju jha",
    "What is your age group?": "35 - 50",
    "What is your occupation?": "Working / Professional",
    "How often do you use public wifi?": "Monthly",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Very Important",
    "What activities do you usually perform on public wifi?": "Browsing social media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "Antivirus / Firewall",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Very secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Sometime",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": ""
  },
  {
    "Timestamp": "9/27/2025 19:20:44",
    "Email Address": "bhainarayan789@gmail.com",
    "Name": "Narayan jha ",
    "What is your age group?": "18 - 25",
    "What is your occupation?": "Business / Entrepreneur",
    "How often do you use public wifi?": "Never",
    "Where do you most often connect to public wifi?": "Airports / Railway stations",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "No activity ",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Not secure at all",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "No",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Security",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Users themselves",
    "Score": ""
  },
  {
    "Timestamp": "10/1/2025 0:53:26",
    "Email Address": "akhtar112101@gmail.com",
    "Name": "akhtar jahan",
    "What is your age group?": "35 - 50",
    "What is your occupation?": "Business / Entrepreneur",
    "How often do you use public wifi?": "Weekly",
    "Where do you most often connect to public wifi?": "Cafes / Restaurants",
    "How important is public wifi to you in your daily routine?": "Not Important",
    "What activities do you usually perform on public wifi?": "Online shopping",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "No",
    "Do you use any security measures while using public wifi?": "Avoiding sensitive transactions",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Paid Wi-Fi services",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "Convenience",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Internet service providers",
    "Score": "0"
  },
  {
    "Timestamp": "2025-10-02T00:21:23.569951",
    "Email Address": "",
    "Name": "",
    "What is your age group?": "18-24",
    "What is your occupation?": "Student",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Cafes/Restaurants",
    "How important is public wifi to you in your daily routine?": "Somewhat Important",
    "What activities do you usually perform on public wifi?": "Browsing/Social Media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "Yes, always",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "Yes",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "Home/Office Wi-Fi",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Yes",
    "What factors influence your decision to connect to a public Wi-Fi network?": "",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Always",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Wi-Fi Providers",
    "Score": "0"
  },
  {
    "Timestamp": "2025-10-27T21:53:40.762001",
    "Email Address": "",
    "Name": "",
    "What is your age group?": "18-24",
    "What is your occupation?": "Freelancer",
    "How often do you use public wifi?": "Daily",
    "Where do you most often connect to public wifi?": "Airports/Train Stations",
    "How important is public wifi to you in your daily routine?": "N/A",
    "What activities do you usually perform on public wifi?": "Browsing/Social Media",
    "Are you aware that using public wifi can pose security risk (eg. data theft, hacking, etc)?": "Yes",
    "Do you use any security measures while using public wifi?": "No",
    "Have you ever faced any security issues while using public wifi (eg. hacking, data lost, suspicious activity)?": "No",
    "How secure do you feel while using public wifi?": "Somewhat secure",
    "If public wifi was not available what alternatives would you prefer?": "N/A",
    "Would you be willing to pay a small fee for safer and more secure public Wi-Fi?": "Maybe",
    "What factors influence your decision to connect to a public Wi-Fi network?": "",
    "Do you read the terms and conditions before connecting to public Wi-Fi?": "Never",
    "In your opinion who should be responsible for ensuring public Wi-Fi security?": "Wi-Fi Providers",
    "Score": "0"
  }
];
